// Client API Constants

// HTTP Status Codes
export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
} as const;

// Error Codes
export const ErrorCode = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_BANNED: 'USER_BANNED',
  DEVICE_LIMIT_EXCEEDED: 'DEVICE_LIMIT_EXCEEDED',

  // Subscription
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  TRAFFIC_EXCEEDED: 'TRAFFIC_EXCEEDED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',

  // Nodes
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',

  // Invites
  INVALID_INVITE_CODE: 'INVALID_INVITE_CODE',
  INVITE_CODE_USED: 'INVITE_CODE_USED',
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
} as const;

// Default Values
export const DEFAULTS = {
  PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  JWT_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '7d',
  RATE_LIMIT_WINDOW_MS: 60000,
  RATE_LIMIT_MAX_REQUESTS: 100,
} as const;

// User Status
export const USER_STATUS = {
  ACTIVE: 1,
  INACTIVE: 0,
  BANNED: 2,
} as const;

// Subscription Status
export const SUBSCRIPTION_STATUS = {
  ACTIVE: 1,
  INACTIVE: 0,
  EXPIRED: 2,
  CANCELLED: 3,
} as const;

// Invite Code Status
export const INVITE_CODE_STATUS = {
  ACTIVE: 1,
  USED: 2,
  EXPIRED: 3,
} as const;

// Order Status
export const ORDER_STATUS = {
  PENDING: 1,
  PAID: 2,
  COMPLETED: 3,
  CANCELLED: 4,
  REFUNDED: 5,
} as const;

// Payment Status
export const PAYMENT_STATUS = {
  PENDING: 1,
  SUCCESS: 2,
  FAILED: 3,
  REFUNDED: 4,
} as const;
