module.exports = {
  apps: [
    {
      name: 'omnicore-client-api',
      script: './src/index.ts',
      interpreter: 'tsx',
      cwd: '/omni-core/apps/client-api',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      log_file: '/var/log/omnicore/client-api-combined.log',
      out_file: '/var/log/omnicore/client-api-out.log',
      error_file: '/var/log/omnicore/client-api-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: 'omnicore-admin-api',
      script: './src/index.ts',
      interpreter: 'tsx',
      cwd: '/omni-core/apps/admin-api',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
        IPDATA_API_KEY: process.env.IPDATA_API_KEY || '',
        DB_HOST: 'localhost',
        DB_PORT: '3306',
        DB_NAME: 'omnicore_admin',
        DB_USER: 'root',
        DB_PASSWORD: 'root123',
      },
      log_file: '/var/log/omnicore/admin-api-combined.log',
      out_file: '/var/log/omnicore/admin-api-out.log',
      error_file: '/var/log/omnicore/admin-api-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: 'omnicore-xray',
      script: '/usr/local/bin/xray',
      args: 'run -c /etc/xray/config.json',
      cwd: '/',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      log_file: '/var/log/xray/xray-combined.log',
      out_file: '/var/log/xray/xray-out.log',
      error_file: '/var/log/xray/xray-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 10000,
      listen_timeout: 15000,
    },
    {
      name: 'omnicore-client-web',
      script: 'npm',
      args: 'run dev -- --host 0.0.0.0 --port 8082',
      cwd: '/omni-core/apps/client-web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
      },
      log_file: '/var/log/omnicore/client-web-combined.log',
      out_file: '/var/log/omnicore/client-web-out.log',
      error_file: '/var/log/omnicore/client-web-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
    {
      name: 'omnicore-admin-web',
      script: 'npm',
      args: 'run dev -- --host 0.0.0.0 --port 8081',
      cwd: '/omni-core/apps/admin-web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
      },
      log_file: '/var/log/omnicore/admin-web-combined.log',
      out_file: '/var/log/omnicore/admin-web-out.log',
      error_file: '/var/log/omnicore/admin-web-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
  ],
};
